function [lb,ub] = bumpShapeBounds(cfg)
%BUMPSHAPEBOUNDS Constrain the PEAK, without masking shallow production.
assert(isequal(size(cfg.bumpBounds),[2,2]) && ...
    all(isfinite(cfg.bumpBounds),'all') && all(cfg.bumpBounds(:,1)>=0) && ...
    all(cfg.bumpBounds(:,2)>0),'methane:BumpBounds','Invalid bump bounds.');
lb=cfg.bumpBounds(1,:); ub=cfg.bumpBounds(2,:);
lb(1)=max(lb(1),cfg.lossDepth);
assert(lb(1)>0 && all(lb<ub),'methane:BumpBounds', ...
    'The constrained peak must be positive and shape intervals nonempty.');
assert(sum(ub)<=cfg.bottomDepth,'methane:BumpBounds', ...
    'The bump support must lie within the sediment domain.');
end
