function exportResults(r)
%EXPORTRESULTS Fitted parameters, profiles, and additive source contributions.
out=r.config.outputDir;
if ~isfolder(out), mkdir(out); end
d=r.diagnostics; cfg=r.config;
writetable(resultSummary(r),fullfile(out,'summary.csv'));
[lb,ub]=bumpShapeBounds(cfg);
parameter=["q";"k_loss";"P0";"Pbg";"z_peak";"w_tail"];
value=[r.qMagnitude;r.kLoss_per_day;r.productionFit.amplitudesScaled/cfg.scaling; ...
    r.productionFit.shape'];
unit=["m/s";"day^-1";"mol/m^3 bulk/s";"mol/m^3 bulk/s";"m";"m"];
lower_bound=[cfg.qBounds(1);cfg.kLossBounds(1);0;0;lb'];
upper_bound=[cfg.qBounds(2);cfg.kLossBounds(2);Inf;Inf;ub'];
fitted=[cfg.fitDarcy;cfg.fitLoss;true;true;true;true];
writetable(table(parameter,value,unit,lower_bound,upper_bound,fitted), ...
    fullfile(out,'parameters.csv'));
writetable(table(r.z,r.concentration,r.fm,r.fmConcentration,r.sourceAge,r.sourceFm, ...
    r.productionScaled/cfg.scaling,d.lossProfile,'VariableNames', ...
    {'depth_m','CH4_mM','methane_Fm','Fm_weighted_CH4_mM','source_age_BP', ...
    'source_Fm','production_mol_m3_bulk_s','loss_mol_m3_bulk_s'}),fullfile(out,'profiles.csv'));
writetable(table(r.z,r.sourceAge,r.sourceFm,d.sourceFraction,d.cumulativeDepthFraction, ...
    d.sourceGrossProduction*86400*1000,d.sourceLoss*86400*1000,d.sourceFlux*86400*1000, ...
    'VariableNames',{'source_depth_m','source_age_BP','source_Fm','export_fraction', ...
    'cumulative_export_fraction','J_gross_mmol_m2_day','J_loss_mmol_m2_day', ...
    'J_export_mmol_m2_day'}),fullfile(out,'source_contributions.csv'));
writetable(table(d.uniqueSourceAge,d.ageFraction,d.cumulativeAgeFraction, ...
    'VariableNames',{'source_age_BP','export_fraction','cumulative_export_fraction'}), ...
    fullfile(out,'source_age_distribution.csv'));
% Preserve the configuration and input paths actually used for this run.
result=r;
save(fullfile(out,'result.mat'),'result');
end
